import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import NavBar from "@/components/common/NavBar";
import SocialIcons from "@/components/common/SocialIcons";
import Developer from "@/components/common/Developer";
import CursorTrailCanvas from "@/components/common/CursorTrailCanvas";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Saad Qadeer Abbasi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <CursorTrailCanvas
            color="hsla(50, 50%, 50%)"
            className="pointer-events-none fixed inset-0 -z-10 h-full w-full"
          />
          <NavBar />
          <SocialIcons />
          <Developer />
          {children}
        </main>
      </body>
    </html>
  );
}
