// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import NavBar from "@/components/common/NavBar";
import SocialIcons from "@/components/common/SocialIcons";
import Developer from "@/components/common/Developer";
import CursorTrailCanvas from "@/components/common/CursorTrailCanvas";
import LoadingWrapper from "@/components/common/LoadingWrapper"; // Import the client-side wrapper
import { LoadingProvider } from "@/context/LoadingContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Saad Qadeer Abbasi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LoadingProvider>
          <LoadingWrapper>
            <CursorTrailCanvas
              color="hsla(50, 50%, 50%)"
              className="pointer-events-none fixed inset-0 -z-10 h-full w-full"
            />
            <NavBar />
            <SocialIcons />
            <Developer />
            {children}
          </LoadingWrapper>
        </LoadingProvider>
      </body>
    </html>
  );
}
